name: binary_data_reader
description: >
  The binary_data_reader is a Dart package designed exclusively for parsing and interpreting the unique binary packet structure utilized across our company's software and hardware ecosystems. This package provides a streamlined and efficient way to convert binary streams into structured data formats, supporting both real-time processing and batch data handling tasks. With support for our proprietary packet formats, including headers, payload data extraction, and error detection, the binary_data_reader is an essential tool for developers working on data integration, analysis, and debugging within our infrastructure.
version: 1.4.3
environment:
  sdk: ^3.3.1
dependencies:
  fake_async: ^1.3.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.0.0
  build_runner: ^2.0.0
