// Mocks generated by Mockito 5.4.4 from annotations
// in coach_app/test/unit/avatars/infrastructure/image_format_service_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:typed_data' as _i4;

import 'package:domain/features/images/services/image_format_detector.dart'
    as _i2;
import 'package:domain/features/images/value_objects/image_format.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ImageFormatDetector].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageFormatDetector extends _i1.Mock
    implements _i2.ImageFormatDetector {
  MockImageFormatDetector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ImageFormat detectFormat(_i4.Uint8List? bytes) => (super.noSuchMethod(
        Invocation.method(
          #detectFormat,
          [bytes],
        ),
        returnValue: _i3.ImageFormat.invalid,
      ) as _i3.ImageFormat);
}
