// Mocks generated by Mockito 5.4.4 from annotations
// in coach_app/test/unit/athletes/data/athletes_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:domain/features/athletes/data/athletes_service.dart' as _i4;
import 'package:domain/features/athletes/data/members_service.dart' as _i11;
import 'package:domain/features/athletes/entities/athlete.dart' as _i2;
import 'package:domain/features/athletes/entities/group_role.dart' as _i12;
import 'package:domain/features/athletes/entities/member.dart' as _i3;
import 'package:domain/features/athletes/value_objects/athlete_filter_criteria.dart'
    as _i6;
import 'package:domain/features/athletes/value_objects/athlete_sort_criteria.dart'
    as _i7;
import 'package:domain/features/logging/entities/log_entry.dart' as _i10;
import 'package:domain/features/logging/repositories/logger.dart' as _i9;
import 'package:domain/features/shared/value_objects/filter_criteria.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAthlete_0 extends _i1.SmartFake implements _i2.Athlete {
  _FakeAthlete_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMember_1 extends _i1.SmartFake implements _i3.Member {
  _FakeMember_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AthletesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAthletesService extends _i1.Mock implements _i4.AthletesService {
  MockAthletesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Athlete>> getAllAthletes() => (super.noSuchMethod(
        Invocation.method(
          #getAllAthletes,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Athlete>>.value(<_i2.Athlete>[]),
      ) as _i5.Future<List<_i2.Athlete>>);

  @override
  _i5.Future<List<_i2.Athlete>> getAthletesByPage(
    int? page,
    int? pageSize, {
    _i6.AthleteFilterCriteria? filterCriteria,
    _i7.AthleteSortCriteria? sortCriteria,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAthletesByPage,
          [
            page,
            pageSize,
          ],
          {
            #filterCriteria: filterCriteria,
            #sortCriteria: sortCriteria,
          },
        ),
        returnValue: _i5.Future<List<_i2.Athlete>>.value(<_i2.Athlete>[]),
      ) as _i5.Future<List<_i2.Athlete>>);

  @override
  _i5.Future<List<_i2.Athlete>> getAthletesByFilterCriteria(
          _i8.FilterCriteria? filterCriteria) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAthletesByFilterCriteria,
          [filterCriteria],
        ),
        returnValue: _i5.Future<List<_i2.Athlete>>.value(<_i2.Athlete>[]),
      ) as _i5.Future<List<_i2.Athlete>>);

  @override
  _i5.Future<_i2.Athlete> getAthleteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getAthleteById,
          [id],
        ),
        returnValue: _i5.Future<_i2.Athlete>.value(_FakeAthlete_0(
          this,
          Invocation.method(
            #getAthleteById,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.Athlete>);

  @override
  _i5.Future<_i2.Athlete> createAthlete(_i2.Athlete? athlete) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAthlete,
          [athlete],
        ),
        returnValue: _i5.Future<_i2.Athlete>.value(_FakeAthlete_0(
          this,
          Invocation.method(
            #createAthlete,
            [athlete],
          ),
        )),
      ) as _i5.Future<_i2.Athlete>);

  @override
  _i5.Future<_i2.Athlete> updateAthlete(_i2.Athlete? athlete) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAthlete,
          [athlete],
        ),
        returnValue: _i5.Future<_i2.Athlete>.value(_FakeAthlete_0(
          this,
          Invocation.method(
            #updateAthlete,
            [athlete],
          ),
        )),
      ) as _i5.Future<_i2.Athlete>);

  @override
  _i5.Future<void> deleteAthlete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAthlete,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Athlete> restoreAthlete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #restoreAthlete,
          [id],
        ),
        returnValue: _i5.Future<_i2.Athlete>.value(_FakeAthlete_0(
          this,
          Invocation.method(
            #restoreAthlete,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.Athlete>);

  @override
  _i5.Future<List<_i2.Athlete>> getAthletesByIds(List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAthletesByIds,
          [ids],
        ),
        returnValue: _i5.Future<List<_i2.Athlete>>.value(<_i2.Athlete>[]),
      ) as _i5.Future<List<_i2.Athlete>>);

  @override
  _i5.Future<void> resetAndRefreshDatabase() => (super.noSuchMethod(
        Invocation.method(
          #resetAndRefreshDatabase,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> initializeDatabase() => (super.noSuchMethod(
        Invocation.method(
          #initializeDatabase,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [LoggerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggerRepository extends _i1.Mock implements _i9.LoggerRepository {
  MockLoggerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i10.LogEntry> get logStream => (super.noSuchMethod(
        Invocation.getter(#logStream),
        returnValue: _i5.Stream<_i10.LogEntry>.empty(),
      ) as _i5.Stream<_i10.LogEntry>);

  @override
  void debug(String? message) => super.noSuchMethod(
        Invocation.method(
          #debug,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message) => super.noSuchMethod(
        Invocation.method(
          #info,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void warning(String? message) => super.noSuchMethod(
        Invocation.method(
          #warning,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, [
    dynamic error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [
            message,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MembersService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMembersService extends _i1.Mock implements _i11.MembersService {
  MockMembersService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.Member>> getMembersForGroup(String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMembersForGroup,
          [groupId],
        ),
        returnValue: _i5.Future<List<_i3.Member>>.value(<_i3.Member>[]),
      ) as _i5.Future<List<_i3.Member>>);

  @override
  _i5.Future<_i3.Member?> getMemberByAthleteAndGroup(
    String? athleteId,
    String? groupId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMemberByAthleteAndGroup,
          [
            athleteId,
            groupId,
          ],
        ),
        returnValue: _i5.Future<_i3.Member?>.value(),
      ) as _i5.Future<_i3.Member?>);

  @override
  _i5.Future<_i3.Member> addMemberToGroup(
    String? athleteId,
    String? groupId,
    _i12.GroupRole? role,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMemberToGroup,
          [
            athleteId,
            groupId,
            role,
          ],
        ),
        returnValue: _i5.Future<_i3.Member>.value(_FakeMember_1(
          this,
          Invocation.method(
            #addMemberToGroup,
            [
              athleteId,
              groupId,
              role,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Member>);

  @override
  _i5.Future<_i3.Member> updateMemberRole(
    String? memberId,
    _i12.GroupRole? newRole,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemberRole,
          [
            memberId,
            newRole,
          ],
        ),
        returnValue: _i5.Future<_i3.Member>.value(_FakeMember_1(
          this,
          Invocation.method(
            #updateMemberRole,
            [
              memberId,
              newRole,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Member>);

  @override
  _i5.Future<void> removeMembersFromGroup(
    String? groupId,
    String? memberIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMembersFromGroup,
          [
            groupId,
            memberIds,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.Member>> getGroupsForAthlete(String? athleteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupsForAthlete,
          [athleteId],
        ),
        returnValue: _i5.Future<List<_i3.Member>>.value(<_i3.Member>[]),
      ) as _i5.Future<List<_i3.Member>>);

  @override
  _i5.Future<bool> isAthleteMemberOfGroup(
    String? athleteId,
    String? groupId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isAthleteMemberOfGroup,
          [
            athleteId,
            groupId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> getMemberCountForGroup(String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMemberCountForGroup,
          [groupId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.Member>> getMembersForGroupPaginated(
    String? groupId,
    int? page,
    int? pageSize,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMembersForGroupPaginated,
          [
            groupId,
            page,
            pageSize,
          ],
        ),
        returnValue: _i5.Future<List<_i3.Member>>.value(<_i3.Member>[]),
      ) as _i5.Future<List<_i3.Member>>);

  @override
  _i5.Future<List<_i3.Member>> searchMembersInGroup(
    String? groupId,
    String? searchTerm,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMembersInGroup,
          [
            groupId,
            searchTerm,
          ],
        ),
        returnValue: _i5.Future<List<_i3.Member>>.value(<_i3.Member>[]),
      ) as _i5.Future<List<_i3.Member>>);

  @override
  _i5.Future<List<_i3.Member>> batchAddMembersToGroup(
    String? groupId,
    List<String>? athleteIds,
    _i12.GroupRole? role,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchAddMembersToGroup,
          [
            groupId,
            athleteIds,
            role,
          ],
        ),
        returnValue: _i5.Future<List<_i3.Member>>.value(<_i3.Member>[]),
      ) as _i5.Future<List<_i3.Member>>);

  @override
  _i5.Future<void> batchRemoveMembersFromGroup(
    String? groupId,
    List<String>? memberIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchRemoveMembersFromGroup,
          [
            groupId,
            memberIds,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, List<_i3.Member>>> getGroupsForAthletes(
          List<String>? athleteIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupsForAthletes,
          [athleteIds],
        ),
        returnValue: _i5.Future<Map<String, List<_i3.Member>>>.value(
            <String, List<_i3.Member>>{}),
      ) as _i5.Future<Map<String, List<_i3.Member>>>);

  @override
  _i5.Future<Map<String, bool>> areAthletesMembersOfGroup(
    List<String>? athleteIds,
    String? groupId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #areAthletesMembersOfGroup,
          [
            athleteIds,
            groupId,
          ],
        ),
        returnValue: _i5.Future<Map<String, bool>>.value(<String, bool>{}),
      ) as _i5.Future<Map<String, bool>>);
}
