name: application
description: Application package that depends on the domain layer
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  domain:
    path: ../domain
  equatable: ^2.0.5

dev_dependencies:
  test: ^1.24.0
  mockito: ^5.0.0
  build_runner: ^2.1.0
  coverage: ^1.9.0
