name: gps_data_analysis
description: A starting point for Dart libraries or applications.
version: 1.1.10
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  rxdart: ^0.27.7
  csv: ^6.0.0
  args: ^2.5.0  
  collection: ^1.18.0
  dart_console: ^4.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
