name: domain
description: Domain package containing all domain code according to clean architecture
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  binary_data_reader:
    path: ../binary_data_reader
  equatable: ^2.0.5
  typed_data: ^1.3.2

dev_dependencies:
  test: ^1.24.0
  mockito: ^5.0.0
  build_runner: ^2.1.0
  coverage: ^1.9.0
